name = "longxiaji-website"
compatibility_date = "2024-03-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "longxiaji_inventory"
database_id = "6487f628-44f2-44e6-a978-065d7e1582d3"